#
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html.
#
Pod::Spec.new do |s|
  s.name             = 'wallet_fhse'
  s.version          = '0.1.0'
  s.summary          = 'FHSE (FIDO2 hmac-secret encryption) for wallet files.'
  s.description      = <<-DESC
vtnerd's FHSE, with libcbor and libsodium, built from vendored sources behind
the small C interface in src/wfhse.h.
                       DESC
  s.homepage         = 'https://github.com/MAGICGrants/wallet-core'
  s.license          = { :type => 'BSD-3-Clause' }
  s.author           = { 'MAGIC Grants' => 'info@magicgrants.org' }

  # Classes/ holds one forwarding file per C source under ../src, generated by
  # tool/generate_ios_classes.sh; a podspec cannot name files outside its
  # directory.
  s.source           = { :path => '.' }
  s.source_files     = 'Classes/**/*.c'
  s.dependency 'Flutter'
  s.platform = :ios, '13.0'

  src = '${PODS_TARGET_SRCROOT}/../src'
  s.pod_target_xcconfig = {
    'DEFINES_MODULE' => 'YES',
    # Flutter.framework does not contain a i386 slice.
    'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'i386',
    # No header maps: CocoaPods' maps index every pod's headers ahead of the
    # search paths, and another pod's version.h shadowed libsodium's.
    'USE_HEADERMAP' => 'NO',
    'HEADER_SEARCH_PATHS' => [
      "\"#{src}\"",
      "\"#{src}/vendor/fhse/include\"",
      "\"#{src}/vendor/fhse/src\"",
      "\"#{src}/vendor/libcbor/src\"",
      "\"#{src}/vendor/libsodium/src/libsodium/include\"",
      "\"#{src}/vendor/libsodium/src/libsodium/include/sodium\"",
    ].join(' '),
    # The same definitions as src/CMakeLists.txt's Apple build; keep in step.
    # libsodium's optimised variants stay disabled, as there. Unlike macOS, the
    # iOS SDK has no <sys/random.h> (so no HAVE_SYS_RANDOM_H or
    # HAVE_GETENTROPY); libsodium takes randomness from arc4random_buf.
    'GCC_PREPROCESSOR_DEFINITIONS' => [
      '$(inherited)',
      'FHSE_LIBSODIUM=1',
      'SODIUM_STATIC=1',
      'CONFIGURED=1',
      'HAVE_ATOMIC_OPS=1',
      'HAVE_C11_MEMORY_FENCES=1',
      'HAVE_GCC_MEMORY_FENCES=1',
      'HAVE_INTTYPES_H=1',
      'HAVE_STDINT_H=1',
      'NATIVE_LITTLE_ENDIAN=1',
      'TLS=_Thread_local',
      'HAVE_CLOCK_GETTIME=1',
      'HAVE_GETPID=1',
      'HAVE_MADVISE=1',
      'HAVE_MLOCK=1',
      'HAVE_MMAP=1',
      'HAVE_MPROTECT=1',
      'HAVE_NANOSLEEP=1',
      'HAVE_POSIX_MEMALIGN=1',
      'HAVE_PTHREAD=1',
      'HAVE_RAISE=1',
      'HAVE_SYSCONF=1',
      'HAVE_SYS_MMAN_H=1',
      'HAVE_SYS_PARAM_H=1',
      'HAVE_WEAK_SYMBOLS=1',
      'HAVE_TI_MODE=1',
      'HAVE_ARC4RANDOM=1',
      'HAVE_ARC4RANDOM_BUF=1',
      'HAVE_MEMSET_S=1',
    ].join(' '),
    'GCC_C_LANGUAGE_STANDARD' => 'gnu11',
    # Only wfhse_* (marked default visibility in wfhse.h) leave the framework.
    # Passed as a flag: GCC_SYMBOLS_PRIVATE_EXTERN did not reach the compile
    # line in a Flutter app's Pods project.
    'OTHER_CFLAGS' => '$(inherited) -fvisibility=hidden -fno-strict-aliasing -fno-strict-overflow -fwrapv',
    'GCC_WARN_INHIBIT_ALL_WARNINGS' => 'YES',
  }
end
