#!/usr/bin/env bash
#
# Regenerates lib/src/testing/test_pki.dart: a throwaway CA hierarchy for the
# TLS tests. Every private key ends up in that file in plain text; nothing it
# signs is trustworthy.
#
#   root CA -> intermediate CA -> server (localhost, wallet-tls.test, 127.0.0.1, ::1)
#                              -> wrong-host (wrong-host.test only)
#   untrusted root CA          -> untrusted server (same names as server)
#
# ECDSA P-256. The CAs are valid for 100 years from today. The server
# certificates run from 2019-06-01 to 2126: Apple's TLS verifier, which Dart
# uses on macOS and iOS, rejects a server certificate valid for more than 825
# days unless it was issued before July 2019. Works with OpenSSL 3 and LibreSSL.
set -euo pipefail

OUT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/lib/src/testing/test_pki.dart"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
cd "$WORK"

DAYS=36500
SERVER_NAMES="DNS:localhost,DNS:wallet-tls.test,IP:127.0.0.1,IP:::1"

key() { openssl ecparam -name prime256v1 -genkey -noout | openssl pkcs8 -topk8 -nocrypt -out "$1"; }
serial() { echo "0x$(openssl rand -hex 8)"; }

root_ca() { # name subject
  key "$1.key"
  printf 'basicConstraints=critical,CA:TRUE\nkeyUsage=critical,keyCertSign,cRLSign\nsubjectKeyIdentifier=hash\n' > "$1.ext"
  openssl req -new -key "$1.key" -subj "$2" -out "$1.csr"
  openssl x509 -req -in "$1.csr" -signkey "$1.key" -days $DAYS -sha256 -extfile "$1.ext" -set_serial "$(serial)" -out "$1.pem" 2>/dev/null
}

issued() { # name subject issuer extensions
  key "$1.key"
  printf '%b' "$4" > "$1.ext"
  openssl req -new -key "$1.key" -subj "$2" -out "$1.csr"
  openssl x509 -req -in "$1.csr" -CA "$3.pem" -CAkey "$3.key" -days $DAYS -sha256 -extfile "$1.ext" -set_serial "$(serial)" -out "$1.pem" 2>/dev/null
}

# `openssl ca` rather than `x509 -req`, which cannot backdate notBefore.
mkdir -p db && touch db/index.txt && echo 1000 > db/serial
cat > ca.cnf <<'CNF'
[ ca ]
default_ca = test_ca
[ test_ca ]
dir = db
database = $dir/index.txt
new_certs_dir = $dir
serial = $dir/serial
default_md = sha256
policy = any_name
unique_subject = no
copy_extensions = none
[ any_name ]
commonName = supplied
CNF

server_cert() { # name common-name issuer subject-alt-names
  key "$1.key"
  printf 'basicConstraints=critical,CA:FALSE\nkeyUsage=critical,digitalSignature\nextendedKeyUsage=serverAuth\nsubjectAltName=%s\nsubjectKeyIdentifier=hash\nauthorityKeyIdentifier=keyid\n' "$4" > "$1.ext"
  openssl req -new -key "$1.key" -subj "/CN=$2" -out "$1.csr"
  openssl ca -batch -notext -config ca.cnf -cert "$3.pem" -keyfile "$3.key" -in "$1.csr" \
    -startdate 190601000000Z -enddate 21260101000000Z -extfile "$1.ext" -out "$1.pem" 2>/dev/null
}

INTERMEDIATE_EXT='basicConstraints=critical,CA:TRUE,pathlen:0\nkeyUsage=critical,keyCertSign,cRLSign\nsubjectKeyIdentifier=hash\nauthorityKeyIdentifier=keyid\n'

root_ca root "/CN=Wallet TLS Test Root CA"
issued intermediate "/CN=Wallet TLS Test Intermediate CA" root "$INTERMEDIATE_EXT"
server_cert server "wallet-tls.test" intermediate "$SERVER_NAMES"
server_cert wrong_host "wrong-host.test" intermediate "DNS:wrong-host.test"
root_ca untrusted_root "/CN=Untrusted Test Root CA"
server_cert untrusted_server "wallet-tls.test" untrusted_root "$SERVER_NAMES"

openssl verify -CAfile root.pem -untrusted intermediate.pem server.pem wrong_host.pem >/dev/null

constant() { # doc name file
  [ -n "$1" ] && printf '  /// %s\n' "$1"
  printf "  static const %s = '''\n" "$2"
  cat "$3"
  printf "''';\n\n"
}

{
  cat <<'EOF'
// Generated by tool/make_test_pki.sh. Do not edit by hand.

/// A throwaway PKI for TLS tests: a root, an intermediate, and server
/// certificates that are valid, issued for the wrong host, or from a root the
/// wallet does not trust.
///
/// Every private key is published right here. Nothing these certificates sign
/// is trustworthy, and none of them may reach a production trust store.
class TestPki {
  TestPki._();

  /// A name the wallet treats as routable, so it insists on TLS. Nothing
  /// resolves it: tests reach it through `SocksTestProxy`, which maps it to a
  /// local server the way Tor carries a name to its destination.
  static const routableHost = 'wallet-tls.test';

EOF
  constant "The trust anchor: the only certificate a test hands the wallet as its CA bundle." rootCa root.pem
  constant "Issued by [rootCa]. Servers send it after their leaf, so chain building is exercised." intermediateCa intermediate.pem
  constant "Valid for \`localhost\`, [routableHost], 127.0.0.1 and ::1; issued by [intermediateCa]." serverCert server.pem
  constant "" serverKey server.key
  constant "Chains to [rootCa] but names only \`wrong-host.test\`." wrongHostCert wrong_host.pem
  constant "" wrongHostKey wrong_host.key
  constant "A root the wallet is never given." untrustedCa untrusted_root.pem
  constant "Names the same hosts as [serverCert] but chains to [untrustedCa]." untrustedServerCert untrusted_server.pem
  constant "" untrustedServerKey untrusted_server.key
  cat <<'EOF'
  /// [serverCert] followed by its issuer, as a server sends it.
  static const serverChain = serverCert + intermediateCa;

  /// [wrongHostCert] followed by its issuer.
  static const wrongHostChain = wrongHostCert + intermediateCa;
}
EOF
} > "$OUT"

echo "wrote $OUT"
