// monero.dart marks its generated surface `@Deprecated("TODO")`; the
// generator's "not yet exercised" marker, not a real deprecation. Same
// file-level suppression as native_spike_test.dart.
// ignore_for_file: deprecated_member_use

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:monero/monero.dart' as monero;
import 'package:wallet_domain/wallet_domain.dart';
import 'package:wallet_infra/testing.dart';
import 'package:wallet_infra/wallet_infra.dart';
import 'package:wallet_monero/wallet_monero.dart';

/// Drives the shared core against the generated Monero test wallets.
///
/// Each is a wallet directory in a state that must not break;
/// generated by `tool/make_fixtures.dart` from published stagenet seeds. This
/// file is the consumer: for every fixture it asserts the minimum contract from
/// the recorded expectations (opens without throwing, the primary address matches the
/// manifest, `hasExistingWallet()` is true) plus whatever that fixture exists to
/// prove.
///
/// Two gates, and they are independent:
///
///   - **the wallets**: generated? `FIXTURE_CORPUS` points at them, default
///     `test_fixtures/wallets`. Absent ⇒ skip, or fail under
///     `REQUIRE_FIXTURE_CORPUS=1`.
///   - **monero_c**: loadable? `MONERO_LIB_PATH`, same convention as
///     `native_spike_test.dart`. Absent ⇒ the wallet-file fixtures skip; the
///     ones that need no FFI still run.
///
/// That split is deliberate: the corruption and plaintext-prefs fixtures are the
/// ones a developer can run on any machine, and they should not be held hostage
/// to a 40-minute Monero build.
bool get _corpusRequired => Platform.environment['REQUIRE_FIXTURE_CORPUS'] == '1';

String get _corpusPath {
  final override = Platform.environment['FIXTURE_CORPUS'];
  // `flutter test` runs with the package directory as CWD.
  return (override != null && override.isNotEmpty) ? override : '../../test_fixtures/wallets';
}

bool _ffiConfigured = false;

/// True when monero_c can be loaded.
bool _ffiAvailable() {
  if (!_ffiConfigured) {
    final override = Platform.environment['MONERO_LIB_PATH'];
    if (override != null && override.isNotEmpty) monero.libPath = override;
    _ffiConfigured = true;
  }
  try {
    monero.WalletManagerFactory_getWalletManager();
    return true;
  } catch (_) {
    return false;
  }
}

/// The fixture's directory, having checked it is actually there.
///
/// A manifest that lists a wallet whose files are gone is broken, not
/// an absent one; the difference matters, because "absent" skips and "broken"
/// must not. Regenerating is always the fix.
Directory _fixtureDir(Directory corpus, String name) {
  final dir = Directory('${corpus.path}/$name');
  if (!dir.existsSync()) {
    fail(
      'MANIFEST.json lists "$name" but ${dir.path} is missing. The wallet files '
      'are not tracked, so regenerate: dart run tool/make_fixtures.dart',
    );
  }
  return dir;
}

/// Copies a fixture aside before it is opened.
///
/// Opening a wallet writes to it; the cache, the address book, sometimes the
/// keys file. A test that opened them in place would mutate the thing it
/// is comparing against and pass on the second run for the wrong reason.
Directory _checkout(Directory fixture) {
  final tmp = Directory.systemTemp.createTempSync('corpus_${fixture.path.split('/').last}');
  for (final entity in fixture.listSync()) {
    if (entity is File) {
      entity.copySync('${tmp.path}/${entity.path.split('/').last}');
    }
  }
  return tmp;
}

void main() {
  final corpus = Directory(_corpusPath);
  final manifestFile = File('${corpus.path}/MANIFEST.json');

  if (!manifestFile.existsSync()) {
    final message =
        'No fixture corpus at ${corpus.path}. Generate one with '
        '`dart run tool/make_fixtures.dart`, or point '
        'FIXTURE_CORPUS at it.';
    test('the fixture corpus is present', () {
      if (_corpusRequired) fail('REQUIRE_FIXTURE_CORPUS=1 but $message');
      markTestSkipped(message);
    }, skip: _corpusRequired ? false : message);
    return;
  }

  final manifest = jsonDecode(manifestFile.readAsStringSync()) as Map<String, dynamic>;
  final fixtures = manifest['fixtures'] as Map<String, dynamic>;
  final password = manifest['password'] as String;

  test('the manifest is a corpus, not an empty shell', () {
    // A generated-but-empty set would let every case below vacuously pass.
    expect(fixtures, isNotEmpty);
    expect(
      manifest['networkType'],
      2,
      reason: 'published seeds must derive stagenet addresses, never mainnet',
    );
  });

  group('wallet-file fixtures', () {
    final ffi = _ffiAvailable();

    for (final entry in fixtures.entries) {
      final spec = entry.value as Map<String, dynamic>;
      final walletFile = spec['walletFile'] as String?;
      if (walletFile == null) continue; // not a wallet-file fixture

      test(entry.key, () async {
        final dir = _checkout(_fixtureDir(corpus, entry.key));
        addTearDown(() => dir.deleteSync(recursive: true));

        // Which app's namer opens this file is part of what the fixture encodes:
        // Skylight writes `mywallet`, Spice `mywallet_xmr`.
        final config = walletFile.startsWith('mywallet_xmr')
            ? WalletAppConfig.spice
            : WalletAppConfig.skylight;
        SharedPreferencesService.store = MemoryPreferenceStore();
        WalletSecrets.store = MemorySecretStore();
        WalletAppConfig.install(config, directories: FixedDirectories(dir));
        addTearDown(() {
          WalletAppConfig.resetForTesting();
          SharedPreferencesService.resetForTesting();
          WalletSecrets.resetForTesting();
        });

        // The persisted connection type decides which file the wallet looks for,
        // which is the whole point of `skylight_node_only`.
        final prefsName = spec['prefs'] as String?;
        if (prefsName != null) {
          final prefs = jsonDecode(File('${dir.path}/$prefsName').readAsStringSync());
          for (final e in (prefs as Map<String, dynamic>).entries) {
            await SharedPreferencesService.set<Object>(
              WalletAppConfig.instance.prefKeyNamer('XMR', e.key),
              e.value as Object,
            );
          }
        } else if (walletFile.endsWith('_node')) {
          await SharedPreferencesService.set<String>(
            WalletAppConfig.instance.prefKeyNamer('XMR', 'connectionType'),
            'node',
          );
        }

        final wallet = MoneroWallet();
        addTearDown(wallet.dispose);

        expect(
          await wallet.hasExistingWallet(),
          isTrue,
          reason: 'the corpus entry exists; the wallet layer must find it',
        );

        await wallet.openExisting(password: password);
        await wallet.loadPrimaryAddress();

        expect(wallet.getPrimaryAddress(), spec['address']);
        expect(wallet.getPrimaryAddress(), isNot(startsWith('4')), reason: 'never mainnet');
      }, skip: ffi ? false : 'needs a monero_c build; set MONERO_LIB_PATH');
    }
  });

  group('fixtures that need no FFI', () {
    setUp(() {
      SharedPreferencesService.store = MemoryPreferenceStore();
      WalletFileCrypto.kdf = const FastTestPbkdf2();
    });
    tearDown(() {
      SharedPreferencesService.resetForTesting();
      WalletAppConfig.resetForTesting();
      WalletFileCrypto.kdf = const WebCryptoPbkdf2();
    });

    test('skylight_plaintext_prefs reads back with no migration step', () async {
      final spec = fixtures['skylight_plaintext_prefs'] as Map<String, dynamic>?;
      if (spec == null) return markTestSkipped('not in this corpus');

      final dir = _fixtureDir(corpus, 'skylight_plaintext_prefs');
      final prefs =
          jsonDecode(File('${dir.path}/${spec['prefs']}').readAsStringSync())
              as Map<String, dynamic>;

      WalletAppConfig.install(WalletAppConfig.skylight, directories: FixedDirectories(dir));
      for (final e in prefs.entries) {
        await SharedPreferencesService.set<Object>(e.key, e.value as Object);
      }

      // Skylight's keys are bare, so a shipped v1.0.11 preferences file is read
      // by the shared core unchanged. No migration, and
      // therefore no migration to get wrong.
      final wallet = MoneroWallet();
      addTearDown(wallet.dispose);
      await wallet.loadPersistedConnection();

      expect(wallet.connectionAddress, prefs['connectionAddress']);
      expect(wallet.connectionType, prefs['connectionType']);
      expect(await wallet.getRestoreHeight(), prefs['walletRestoreHeight']);
    });

    for (final name in ['corrupt_truncated', 'corrupt_bad_gcm_tag']) {
      test('$name degrades to no cache rather than throwing', () async {
        final spec = fixtures[name] as Map<String, dynamic>?;
        if (spec == null) return markTestSkipped('not in this corpus');

        final source = File('${_fixtureDir(corpus, name).path}/${spec['cacheFile']}');
        final dir = Directory.systemTemp.createTempSync(name);
        addTearDown(() => dir.deleteSync(recursive: true));
        source.copySync('${dir.path}/xmr_cache');

        WalletAppConfig.install(WalletAppConfig.skylight, directories: FixedDirectories(dir));

        // A cache is derived data. An unreadable one must mean "re-sync", never
        // an exception into a caller that is only trying to show a balance.
        expect(await WalletCacheStore.load('XMR', 'fixture-password'), isEmpty);
      });
    }
  });
}
