import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:bip32/bip32.dart' as bip32;
import 'package:bip39/bip39.dart' as bip39;
import 'package:blockchain_utils/blockchain_utils.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:wallet_monero/wallet_monero.dart';

/// Cross-checks the test wallets' recorded addresses against a second, independent
/// implementation**.
///
/// Why this file exists: `MANIFEST.json` is generated by driving monero_c, so
/// diffing it against monero_c proves only that monero_c is deterministic. A
/// wrong-but-consistent derivation would be recorded as the known answer and
/// every later `--verify` run would defend it. `blockchain_utils` derives Monero
/// addresses in pure Dart, from the same private spend key, with no shared code;
/// so agreement between the two is evidence rather than tautology.
///
/// It also needs no monero_c and no wallet files, only the committed manifest, so
/// it runs on **every push** rather than nightly.
///
/// Keep in step with `tool/make_fixtures.dart`: the constants below are that
/// script's inputs, and a test asserting the manifest matches inputs nobody
/// checked would be theatre.

/// `_bip39` in the generator.
const _bip39Mnemonic =
    'abandon abandon abandon abandon abandon abandon abandon abandon '
    'abandon abandon abandon abandon abandon abandon address';

/// The BIP44 path `getLegacySeedFromBip39` derives the spend key at. SLIP-44
/// coin type 128 is Monero's and long predates any wallet's BIP39 support; this
/// is the standard, not our choice, and users' funds sit behind it.
const _spendKeyPath = "m/44'/128'/0'/0/0";

/// The ed25519 group order the spend key is reduced modulo.
const _curveOrder = '1000000000000000000000000000000014DEF9DEA2F79CD65812631A5CF5D3ED';

/// Fixtures the generator builds from the 25-word seed, so all six must record
/// one identical address.
const _legacyFixtures = [
  'skylight_lws_legacy25',
  'skylight_node',
  'skylight_both_modes',
  'skylight_node_only',
  'spice_v2_xmr',
  'spice_v1_legacy',
];

/// Reproduces `getLegacySeedFromBip39`'s spend key, independently of it.
///
/// Deliberately not a call to that function: this is the check, so computing it
/// with the code under test would compare a value to itself.
Uint8List _spendKeyFromBip39(String mnemonic) {
  final seed = bip39.mnemonicToSeed(mnemonic);
  final keyPair = bip32.BIP32.fromSeed(seed).derivePath(_spendKeyPath);

  var value = BigInt.zero;
  final priv = keyPair.privateKey!;
  for (var i = priv.length - 1; i >= 0; i--) {
    value = value * BigInt.from(256) + BigInt.from(priv[i]);
  }
  value %= BigInt.parse(_curveOrder, radix: 16);

  final out = Uint8List(32);
  for (var i = 0; i < 32; i++) {
    out[i] = (value & BigInt.from(0xff)).toInt();
    value = value >> 8;
  }
  return out;
}

void main() {
  final manifestFile = File('../../test_fixtures/wallets/MANIFEST.json');

  if (!manifestFile.existsSync()) {
    test('the corpus manifest is committed', () {
      markTestSkipped('no MANIFEST.json yet; run tool/make_fixtures.dart');
    }, skip: 'no MANIFEST.json yet; run tool/make_fixtures.dart');
    return;
  }

  final manifest = jsonDecode(manifestFile.readAsStringSync()) as Map<String, dynamic>;
  final fixtures = manifest['fixtures'] as Map<String, dynamic>;

  String? recordedAddress(String fixture) =>
      (fixtures[fixture] as Map<String, dynamic>?)?['address'] as String?;

  test('the derivation path is the standard, and pinned', () {
    // Changing this silently produces a *valid but empty* wallet: no error, no
    // funds, and the user's real balance reachable only by whoever works out
    // what changed. bip39_legacy.dart says the same thing at more length.
    expect(_spendKeyPath, "m/44'/128'/0'/0/0");
  });

  test('the 25-word seed is what the pinned mnemonic derives', () {
    // The generator derives it rather than hardcoding it, after a hardcoded
    // phrase copied from a fake-backend test turned out to fail monero_c's
    // checksum 35 minutes into a CI run. This pins the derivation is stable.
    final seed = getLegacySeedFromBip39(_bip39Mnemonic);
    expect(seed.split(' ').length, 25);
    expect(
      seed,
      'galaxy rounded ability vinegar betting light natural token toffee '
      'gemstone maul dreams sphere offend tomorrow rash awkward seismic doing '
      'unquoted gags aztec maze medicate token',
    );
  });

  test('blockchain_utils agrees with monero_c on the recorded address', () {
    final recorded = recordedAddress('skylight_lws_legacy25');
    if (recorded == null) {
      return markTestSkipped(
        'skylight_lws_legacy25 has no address yet — the manifest was generated '
        'without monero_c. Run native.yml and commit the result.',
      );
    }

    final independent = Monero.fromPrivateSpendKey(
      _spendKeyFromBip39(_bip39Mnemonic),
      coinType: MoneroCoins.moneroStagenet,
    ).primaryAddress;

    // Two implementations, no shared code: monero_c's C++ wallet2 built in CI,
    // and this pure-Dart one. If they ever disagree, one of them changed and it
    // matters which.
    expect(independent, recorded);
  });

  test('every fixture built from the 25-word seed records the same address', () {
    final recorded = {
      for (final name in _legacyFixtures)
        if (recordedAddress(name) != null) name: recordedAddress(name),
    };
    if (recorded.isEmpty) return markTestSkipped('no wallet-file fixtures recorded yet');

    // They share a seed, so they must share an address whatever the file is
    // called or which mode wrote it. A mismatch would mean the wallet *file*
    // influenced the derivation, which it must not.
    expect(recorded.values.toSet(), hasLength(1), reason: 'differing: $recorded');
  });

  test('the polyseed fixture is a different wallet, not a copy', () {
    final poly = recordedAddress('skylight_lws_polyseed');
    final legacy = recordedAddress('skylight_lws_legacy25');
    if (poly == null || legacy == null) return markTestSkipped('not recorded yet');

    // Guards the generator wiring rather than the crypto: passing the wrong seed
    // constant to the polyseed factory would still produce a valid wallet.
    expect(poly, isNot(legacy));
  });

  test('no recorded address is on mainnet', () {
    final addresses = [
      for (final spec in fixtures.values)
        if ((spec as Map<String, dynamic>)['address'] != null) spec['address'] as String,
    ];
    if (addresses.isEmpty) return markTestSkipped('no addresses recorded yet');

    for (final address in addresses) {
      // Stagenet standard addresses start with '5'; mainnet with '4'. Every seed
      // in the generator is published, so a mainnet address here would be an
      // invitation to lose money.
      expect(address, startsWith('5'), reason: address);
      expect(address, hasLength(95));
    }
    expect(manifest['networkType'], 2);
  });
}
