#!/bin/sh
# Regenerates ios/Classes: one forwarding file per C source under src/.
#
# CocoaPods cannot reference files outside the pod's directory, so the iOS
# build compiles src/ through these. One file each, rather than a few that
# include many, because libsodium's sources reuse static function names across
# files; and named after the full path because FHSE has public/ and private/
# files with the same basename.
#
# Run after re-vendoring anything under src/vendor or adding a source to src/.
set -eu
cd "$(dirname "$0")/.."
rm -f ios/Classes/*.c
find src -name '*.c' | LC_ALL=C sort | while read -r source; do
  name=$(printf '%s' "${source#src/}" | sed 's|/|__|g')
  printf '// Generated by tool/generate_ios_classes.sh from %s; do not edit.\n#include "../../%s"\n' \
    "$source" "$source" > "ios/Classes/$name"
done
echo "$(ls ios/Classes/*.c | wc -l | tr -d ' ') forwarding files in ios/Classes"
