// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_kem/mlkem768/kem_mlkem768.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_kem/mlkem768/kem_mlkem768.c"
