// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_core/hsalsa20/core_hsalsa20.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_core/hsalsa20/core_hsalsa20.c"
