// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_aead/aes256gcm/aead_aes256gcm.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_aead/aes256gcm/aead_aes256gcm.c"
