// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_xof/shake256/ref/shake256_ref.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_xof/shake256/ref/shake256_ref.c"
