// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_hash/sha256/cp/hash_sha256_cp.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_hash/sha256/cp/hash_sha256_cp.c"
