// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_xof/shake128/xof_shake128.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_xof/shake128/xof_shake128.c"
