// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_stream/salsa20/ref/salsa20_ref.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_stream/salsa20/ref/salsa20_ref.c"
