// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_aead/aegis256/aegis256_soft.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_aead/aegis256/aegis256_soft.c"
