// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_auth/hmacsha512256/auth_hmacsha512256.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_auth/hmacsha512256/auth_hmacsha512256.c"
