// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_stream/salsa2012/stream_salsa2012.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_stream/salsa2012/stream_salsa2012.c"
