// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_core/ed25519/ref10/ed25519_ref10.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_core/ed25519/ref10/ed25519_ref10.c"
