// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_core/hchacha20/core_hchacha20.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_core/hchacha20/core_hchacha20.c"
