// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_scalarmult/curve25519/scalarmult_curve25519.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_scalarmult/curve25519/scalarmult_curve25519.c"
