// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/randombytes/randombytes.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/randombytes/randombytes.c"
