// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_generichash/blake2b/generichash_blake2.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_generichash/blake2b/generichash_blake2.c"
