// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_generichash/blake2b/ref/generichash_blake2b.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_generichash/blake2b/ref/generichash_blake2b.c"
