// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_aead/aegis128l/aegis128l_soft.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_aead/aegis128l/aegis128l_soft.c"
