// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_auth/hmacsha512/auth_hmacsha512.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_auth/hmacsha512/auth_hmacsha512.c"
