// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_kem/mlkem768/ref/kem_mlkem768_ref.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_kem/mlkem768/ref/kem_mlkem768_ref.c"
