// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_hash/sha512/cp/hash_sha512_cp.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_hash/sha512/cp/hash_sha512_cp.c"
