// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_stream/chacha20/ref/chacha20_ref.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_stream/chacha20/ref/chacha20_ref.c"
