// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_aead/xchacha20poly1305/aead_xchacha20poly1305.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_aead/xchacha20poly1305/aead_xchacha20poly1305.c"
