// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_aead/aegis128l/aead_aegis128l.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_aead/aegis128l/aead_aegis128l.c"
