// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_hash/sha512/hash_sha512.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_hash/sha512/hash_sha512.c"
