// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_core/ed25519/core_ed25519.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_core/ed25519/core_ed25519.c"
