// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_sign/ed25519/sign_ed25519.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_sign/ed25519/sign_ed25519.c"
