// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_hash/crypto_hash.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_hash/crypto_hash.c"
