// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_kem/xwing/kem_xwing.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_kem/xwing/kem_xwing.c"
