// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_onetimeauth/crypto_onetimeauth.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_onetimeauth/crypto_onetimeauth.c"
