// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_sign/crypto_sign.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_sign/crypto_sign.c"
