// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_pwhash/argon2/argon2.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_pwhash/argon2/argon2.c"
