// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_shorthash/siphash24/shorthash_siphashx24.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_shorthash/siphash24/shorthash_siphashx24.c"
