// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_stream/salsa208/ref/stream_salsa208_ref.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_stream/salsa208/ref/stream_salsa208_ref.c"
