// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_auth/crypto_auth.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_auth/crypto_auth.c"
