// Generated by tool/generate_ios_classes.sh from src/vendor/libsodium/src/libsodium/crypto_auth/hmacsha256/auth_hmacsha256.c; do not edit.
#include "../../src/vendor/libsodium/src/libsodium/crypto_auth/hmacsha256/auth_hmacsha256.c"
