// Generates the Monero test wallets: one directory per state that must not
// break.
//
// Run from this package:
//
//   MONERO_LIB_PATH=/abs/path/libwallet2_api_c.so dart run tool/make_fixtures.dart
//   dart run tool/make_fixtures.dart --verify
//
// Writes to `test_fixtures/wallets/` at the repo root by default; the location
// `.gitignore` already reserves, where only MANIFEST.json is tracked. `--out`
// overrides it.
//
// A plain Dart script, not a Flutter test: it runs in CI right after monero_c
// is built, with no engine and no device. It talks to `package:monero` directly
// rather than through `MoneroBackend`, since generating them through the
// code under test would be circular.
//
// monero.dart marks its generated surface `@Deprecated("TODO")`; that is the
// generator's "not yet exercised" marker, not a real deprecation.
// ignore_for_file: deprecated_member_use

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:bip39/bip39.dart' as bip39;
import 'package:monero/monero.dart' as monero;
import 'package:polyseed/polyseed.dart';

// Reached into by path, not through the package barrel. `wallet_monero.dart`
// re-exports files that import `package:flutter`, which needs `dart:ui` and so
// cannot load outside the Flutter engine; this one file is pure Dart (bip32,
// bip39, polyseed). Keeping the tool engine-free is what lets CI run it the
// moment monero_c finishes building.
import 'package:wallet_monero/src/seed/bip39_legacy.dart';

/// Stagenet. Monero's `NetworkType`: 0 mainnet, 1 testnet, 2 stagenet.
///
/// **Every seed below is committed in the clear, so no fixture may derive a
/// mainnet address.** Stagenet makes that a property rather than a promise: the
/// addresses these produce cannot hold mainnet value at all. `recoveryWallet`
/// gained a `networkType` parameter for exactly this; before that, half the
/// wallets would have had to be mainnet.
const int _stagenet = 2;

/// Password every fixture wallet is sealed with. Published on purpose: a fixture
/// nobody can open is not a fixture.
const String _password = 'fixture-password';

/// One kdf round. These are throwaway wallets read thousands of times in CI, and
/// the production count would dominate the build.
const int _kdfRounds = 1;

/// A published BIP39 mnemonic. Never fund this.
///
/// The 25-word seed is *derived* from this rather than hardcoded, via the repo's
/// own `getLegacySeedFromBip39`. The first attempt hardcoded a 25-word phrase
/// copied out of a fake-backend unit test, where nothing ever validated it; a
/// 35-minute CI run then died on `Checksum mismatch` from monero_c. Deriving it
/// makes the seed valid by construction, and `bip39_legacy_test` already pins
/// that derivation with known-answer vectors.
const String _bip39 =
    'abandon abandon abandon abandon abandon abandon abandon abandon '
    'abandon abandon abandon abandon abandon abandon address';

/// A published 16-word polyseed. Never fund this.
///
/// Generated by `Polyseed.create()`, so its checksum is real; the phrase this
/// replaced was invented and failed verification. [_checkSeeds] re-verifies it on
/// every run, in pure Dart, before monero_c is touched.
const String _polyseed =
    'eagle make win stable gift guide few series obscure envelope '
    'oblige inflict over proof assault gossip';

/// The 25-word seed, derived from [_bip39].
final String _legacy25 = getLegacySeedFromBip39(_bip39);

/// The restore height every recovered wallet starts from. Fixed so the output
/// is reproducible.
const int _restoreHeight = 1731707;

/// Shipped v1.0.11 preference values, in the clear.
/// Deliberately *not* balances or transaction history: those already live inside
/// the wallet file's own encrypted cache, so they were never the exposure.
const Map<String, Object> _plaintextPrefs = {
  'connectionAddress': 'stagenet.example.com:38089',
  'connectionType': 'lws',
  'walletRestoreHeight': _restoreHeight,
  'unusedSubaddressIndex': 3,
  'serverSupportsSubaddresses': true,
};

void main(List<String> args) {
  final outIndex = args.indexOf('--out');
  final outPath = outIndex >= 0 && outIndex + 1 < args.length
      ? args[outIndex + 1]
      : '${_repoRoot()}/test_fixtures/wallets';
  final verify = args.contains('--verify');

  // Before anything touches monero_c. The first version of this script shipped
  // two invented seeds and found out from a `Checksum mismatch` thrown by
  // wallet2, 35 minutes into a CI run, having built Monero from source first.
  // These checks are pure Dart and cost milliseconds.
  _checkSeeds();

  final libPath = Platform.environment['MONERO_LIB_PATH'];
  if (libPath != null && libPath.isNotEmpty) monero.libPath = libPath;

  final root = Directory(outPath);
  final manifestFile = File('${root.path}/MANIFEST.json');

  final wm = _tryGetWalletManager();
  if (wm == null) {
    stderr.writeln(
      'monero_c could not be loaded (libPath="${monero.libPath}").\n'
      'The wallet-file fixtures need it; set MONERO_LIB_PATH to an absolute\n'
      'libwallet2_api_c path. Build one with scripts/build-moneroc-ci.sh.\n'
      'Generating the fixtures that do not need it and stopping.',
    );
  }

  // A verify run must never write into the tracked wallets, or it would "fix" the
  // very drift it is checking for.
  final target = verify
      ? Directory.systemTemp.createTempSync('fixture_verify')
      : (root..createSync(recursive: true));

  final entries = <String, Object?>{};
  final failures = <String>[];
  for (final fixture in _fixtures) {
    if (fixture.needsFfi && wm == null) {
      stdout.writeln('skip  ${fixture.name} (needs monero_c)');
      continue;
    }
    final dir = Directory('${target.path}/${fixture.name}')..createSync(recursive: true);
    // Per fixture, so one bad entry reports itself and the rest still run.
    // Letting this throw is how the first CI run exited 255 having uploaded
    // nothing at all: the failure came from the *first* wallet fixture, so the
    // other six were never attempted and the manifest was never written.
    try {
      entries[fixture.name] = fixture.build(wm, dir);
      stdout.writeln('built ${fixture.name}');
    } catch (e) {
      stdout.writeln('FAIL  ${fixture.name}: $e');
      failures.add('${fixture.name}: $e');
    }
  }

  final generated = {
    'note':
        'Generated by packages/wallet_monero/tool/make_fixtures.dart. '
        'Every seed here is published; no fixture holds mainnet value.',
    'networkType': _stagenet,
    'password': _password,
    'fixtures': entries,
  };

  if (verify) {
    _verifyAgainst(manifestFile, generated, target, failures);
    return;
  }

  manifestFile.writeAsStringSync('${const JsonEncoder.withIndent('  ').convert(generated)}\n');
  stdout.writeln('\nwrote ${manifestFile.path}');
  stdout.writeln(
    'Commit MANIFEST.json and nothing else — the wallet files are regenerated,\n'
    'not tracked. From then on `--verify` is a known-answer gate on the whole\n'
    'stack: a changed address means a changed derivation.',
  );
  if (failures.isNotEmpty) {
    // Written anyway, so the partial output is inspectable, but non-zero, so
    // nothing downstream mistakes it for complete.
    stderr.writeln('\n${failures.length} fixture(s) failed to build:\n  ${failures.join('\n  ')}');
    exit(1);
  }
}

void _verifyAgainst(
  File manifestFile,
  Map<String, Object?> generated,
  Directory scratch,
  List<String> failures,
) {
  // Always written, pass or fail, next to the committed manifest and ignored by
  // git. Without it a failing verify leaves nothing to look at: the working tree
  // still holds the *committed* manifest, so CI would upload that and the first
  // run (which fails by design, having no known answers yet) could never hand
  // you the file it is asking you to commit.
  final generatedFile = File('${manifestFile.parent.path}/MANIFEST.generated.json');
  generatedFile.parent.createSync(recursive: true);
  generatedFile.writeAsStringSync('${const JsonEncoder.withIndent('  ').convert(generated)}\n');
  stdout.writeln('wrote ${generatedFile.path}');

  if (!manifestFile.existsSync()) {
    stderr.writeln(
      'No committed manifest at ${manifestFile.path}.\n'
      'Commit ${generatedFile.path} as MANIFEST.json to record the known answers.',
    );
    exit(2);
  }

  final committed = jsonDecode(manifestFile.readAsStringSync()) as Map<String, dynamic>;
  final expected = committed['fixtures'] as Map<String, dynamic>;
  final actual = generated['fixtures']! as Map<String, Object?>;

  // Kept apart because they mean opposite things. A *differing* entry is drift;
  // the derivation changed under you. An entry the manifest has never seen is a
  // bootstrap: new fixture, or the first run on a machine that can build the
  // FFI ones. Reporting both as "does not match" sent people looking for a bug
  // that was not there.
  final drifted = <String>[];
  final unrecorded = <String>[];

  for (final name in expected.keys) {
    if (!actual.containsKey(name)) {
      // Not a failure: a run without monero_c legitimately skips those.
      stdout.writeln('skip  $name (not generated in this run)');
      continue;
    }
    final want = jsonEncode(expected[name]);
    final got = jsonEncode(actual[name]);
    if (want == got) {
      stdout.writeln('ok    $name');
    } else {
      drifted.add('$name:\n  committed: $want\n  generated: $got');
    }
  }
  for (final name in actual.keys) {
    if (!expected.containsKey(name)) unrecorded.add(name);
  }

  scratch.deleteSync(recursive: true);

  if (failures.isNotEmpty) {
    stderr.writeln(
      '\nBUILD FAILURES — these could not be generated at all, so nothing was\n'
      'compared for them:\n\n  ${failures.join('\n  ')}',
    );
  }

  if (drifted.isEmpty && unrecorded.isEmpty && failures.isEmpty) {
    stdout.writeln('\nCorpus matches the committed manifest.');
    return;
  }

  if (drifted.isNotEmpty) {
    stderr.writeln('\nDRIFT — these no longer match the committed manifest:\n');
    stderr.writeln(drifted.join('\n\n'));
    stderr.writeln(
      '\nA changed address means the derivation changed: either the bug you were\n'
      'looking for, or a deliberate change whose manifest update belongs in the\n'
      'same commit.',
    );
  }
  if (unrecorded.isNotEmpty) {
    stderr.writeln(
      '\nNOT YET RECORDED — generated, but the committed manifest has no known\n'
      'answer for them:\n\n  ${unrecorded.join('\n  ')}\n\n'
      'Expected on a first run with monero_c available. Commit\n'
      '${generatedFile.path} as MANIFEST.json and this goes green.',
    );
  }
  exit(1);
}

/// The repo root, from this script's own location rather than the working
/// directory; so it does not matter where it is invoked from.
String _repoRoot() => Directory.fromUri(
  Platform.script.resolve('../../../'),
).absolute.path.replaceAll(RegExp(r'/$'), '');

/// Verifies every seed constant in pure Dart, and stops if one is bad.
///
/// The polyseed carries its own checksum, so `Polyseed.decode` is a real check.
/// The 25-word seed's checksum lives in the Monero word list and `package:polyseed`
/// exposes no verifying decode, which is exactly why it is derived from [_bip39]
/// rather than pinned as a string: `LegacySeedLang.encodePhrase` appends the
/// checksum word itself, so a derived phrase cannot be wrong in that way.
void _checkSeeds() {
  if (!bip39.validateMnemonic(_bip39)) {
    stderr.writeln('_bip39 is not a valid BIP39 mnemonic.');
    exit(2);
  }

  try {
    Polyseed.decode(_polyseed, PolyseedLang.getByPhrase(_polyseed), PolyseedCoin.POLYSEED_MONERO);
  } catch (e) {
    // The catch is untyped on purpose: polyseed 0.0.7 raises a checksum
    // mismatch with `throw ChecksumMismatchException`, the *type*, not an
    // instance; so `on ChecksumMismatchException` never matches it.
    stderr.writeln(
      '_polyseed failed verification (${e.runtimeType}). Generate a real one:\n'
      "  Polyseed.create().encode(PolyseedLang.getByEnglishName('English'), "
      'PolyseedCoin.POLYSEED_MONERO)',
    );
    exit(2);
  }

  final words = _legacy25.split(' ').length;
  if (words != 25) {
    stderr.writeln('the derived legacy seed has $words words, expected 25.');
    exit(2);
  }

  stdout.writeln('seeds ok (polyseed checksum verified, 25-word derived from BIP39)');
}

monero.WalletManager? _tryGetWalletManager() {
  try {
    return monero.WalletManagerFactory_getWalletManager();
  } catch (_) {
    return null;
  }
}

// ----- Fixtures -----

class _Fixture {
  const _Fixture(this.name, this.needsFfi, this.build);

  final String name;
  final bool needsFfi;

  /// Populates [dir] and returns the manifest entry for it.
  final Map<String, Object?> Function(monero.WalletManager? wm, Directory dir) build;
}

/// The wallets.
///
/// Two entries from testing.md's table are deliberately absent:
/// `no_secret_service` and `app_lock_on_cold_start`. Neither is a wallet
/// directory; they are runtime-environment scenarios (a Linux box with no
/// Secret Service provider; a cold start with app lock on) and belong in the
/// app's own integration tier, which is the only place that can arrange them.
/// Inventing directories for them here would look like coverage and provide none.
final List<_Fixture> _fixtures = [
  // v1.0.12 LWS wallet created from a generated polyseed. `newWallet: true` is
  // the created-not-restored path.
  _Fixture('skylight_lws_polyseed', true, (wm, dir) {
    final address = _polyseedWallet(wm!, path: '${dir.path}/mywallet', newWallet: true);
    return {'walletFile': 'mywallet', 'address': address, 'restoreHeight': 0, 'txCount': 0};
  }),

  // LWS wallet restored from a 25-word legacy seed.
  _Fixture('skylight_lws_legacy25', true, (wm, dir) {
    final address = _recoveredWallet(wm!, path: '${dir.path}/mywallet', mnemonic: _legacy25);
    return {
      'walletFile': 'mywallet',
      'address': address,
      'restoreHeight': _restoreHeight,
      'txCount': 0,
    };
  }),

  // Node-mode wallet: Skylight names the other mode's file `mywallet_node`.
  _Fixture('skylight_node', true, (wm, dir) {
    final address = _recoveredWallet(wm!, path: '${dir.path}/mywallet_node', mnemonic: _legacy25);
    return {
      'walletFile': 'mywallet_node',
      'address': address,
      'restoreHeight': _restoreHeight,
      'txCount': 0,
    };
  }),

  // Both mode files present. The two share a seed, so they must share an address.
  _Fixture('skylight_both_modes', true, (wm, dir) {
    final lws = _recoveredWallet(wm!, path: '${dir.path}/mywallet', mnemonic: _legacy25);
    final node = _recoveredWallet(wm, path: '${dir.path}/mywallet_node', mnemonic: _legacy25);
    if (lws != node) {
      throw StateError('the two modes derived different addresses from one seed');
    }
    return {
      'walletFile': 'mywallet',
      'address': lws,
      'restoreHeight': _restoreHeight,
      'txCount': 0,
    };
  }),

  // The `_adoptModeWithExistingWallet` case, and the highest-severity
  // Mismatch case: only the node file exists, while the prefs say `lws`.
  // Spice reports "no wallet" here and drops the user into onboarding on top of
  // an existing wallet.
  _Fixture('skylight_node_only', true, (wm, dir) {
    final address = _recoveredWallet(wm!, path: '${dir.path}/mywallet_node', mnemonic: _legacy25);
    File('${dir.path}/prefs.json').writeAsStringSync(
      jsonEncode({'connectionType': 'lws', 'connectionAddress': 'stagenet.example.com:38089'}),
    );
    return {
      'walletFile': 'mywallet_node',
      'prefs': 'prefs.json',
      'address': address,
      'restoreHeight': _restoreHeight,
      'txCount': 0,
      'expects': 'the wallet layer switches connectionType to "node" rather than reporting none',
    };
  }),

  // Spice v2 names its files per coin.
  _Fixture('spice_v2_xmr', true, (wm, dir) {
    final address = _recoveredWallet(wm!, path: '${dir.path}/mywallet_xmr', mnemonic: _legacy25);
    _recoveredWallet(wm, path: '${dir.path}/mywallet_xmr_node', mnemonic: _legacy25);
    return {
      'walletFile': 'mywallet_xmr',
      'address': address,
      'restoreHeight': _restoreHeight,
      'txCount': 0,
    };
  }),

  // Spice v1's bare `mywallet`, the LegacyMoneroWallet migration. Identical on
  // disk to Skylight's LWS file, which is the point: the migration has to tell
  // them apart from the prefs, not the filename.
  _Fixture('spice_v1_legacy', true, (wm, dir) {
    final address = _recoveredWallet(wm!, path: '${dir.path}/mywallet', mnemonic: _legacy25);
    return {
      'walletFile': 'mywallet',
      'address': address,
      'restoreHeight': _restoreHeight,
      'txCount': 0,
    };
  }),

  // ----- No FFI needed below -----

  // Shipped v1.0.11 prefs, in the clear.
  _Fixture('skylight_plaintext_prefs', false, (wm, dir) {
    File('${dir.path}/prefs.json').writeAsStringSync(jsonEncode(_plaintextPrefs));
    return {
      'prefs': 'prefs.json',
      'keys': _plaintextPrefs.keys.toList(),
      'expects': 'these read back through the wallet layer with no migration step',
    };
  }),

  // A wallet file cut mid-write. `WalletManager.isCorruptWalletFile` must treat
  // this as "delete and re-bootstrap from the stored seed", not as a hard error.
  _Fixture('corrupt_truncated', false, (wm, dir) {
    final blob = base64.encode(_envelope(plaintextLength: 64));
    File('${dir.path}/xmr_cache').writeAsStringSync(blob.substring(0, blob.length ~/ 3));
    return {'cacheFile': 'xmr_cache', 'expects': 'WalletCacheStore.load returns an empty map'};
  }),

  // A structurally valid envelope whose ciphertext has one flipped bit, so the
  // GCM tag check fails. Built by hand rather than by encrypting-then-corrupting
  // so the fixture does not depend on the encryptor it is used to test.
  _Fixture('corrupt_bad_gcm_tag', false, (wm, dir) {
    final bytes = _envelope(plaintextLength: 64);
    bytes[bytes.length - 1] ^= 0x01;
    File('${dir.path}/xmr_cache').writeAsStringSync(base64.encode(bytes));
    return {
      'cacheFile': 'xmr_cache',
      'expects': 'WalletCacheStore.load returns an empty map, and does not throw',
    };
  }),
];

/// A `WalletFileCrypto` envelope: `magic(4) | version(1) | iterations(4) |
/// salt(32) | iv(12) | ct+tag`.
///
/// Deterministic filler, because output that changes every run cannot be a
/// known-answer test. The ciphertext is nonsense; for both corruption fixtures
/// that is exactly the point.
Uint8List _envelope({required int plaintextLength}) {
  final out = BytesBuilder()
    ..add(const [0x53, 0x4B, 0x4C, 0x57]) // 'SKLW'
    ..addByte(1)
    ..add(Uint8List(4)..buffer.asByteData().setUint32(0, 600000, Endian.big))
    ..add(Uint8List.fromList(List<int>.generate(32, (i) => i)))
    ..add(Uint8List.fromList(List<int>.generate(12, (i) => 200 - i)))
    ..add(Uint8List.fromList(List<int>.generate(plaintextLength + 16, (i) => (i * 7) & 0xff)));
  return out.toBytes();
}

// ----- monero_c helpers -----

String _polyseedWallet(monero.WalletManager wm, {required String path, required bool newWallet}) {
  final wallet = monero.WalletManager_createWalletFromPolyseed(
    wm,
    path: path,
    password: _password,
    networkType: _stagenet,
    mnemonic: _polyseed,
    seedOffset: '',
    newWallet: newWallet,
    restoreHeight: newWallet ? 0 : _restoreHeight,
    kdfRounds: _kdfRounds,
  );
  return _finish(wm, wallet, path);
}

String _recoveredWallet(monero.WalletManager wm, {required String path, required String mnemonic}) {
  final wallet = monero.WalletManager_recoveryWallet(
    wm,
    path: path,
    password: _password,
    mnemonic: mnemonic,
    networkType: _stagenet,
    restoreHeight: _restoreHeight,
    kdfRounds: _kdfRounds,
    seedOffset: '',
  );
  return _finish(wm, wallet, path);
}

/// Checks the factory succeeded, flushes the file, and returns the address.
String _finish(monero.WalletManager wm, monero.wallet wallet, String path) {
  final error = monero.Wallet_errorString(wallet);
  if (error.isNotEmpty) {
    throw StateError('building $path failed (status ${monero.Wallet_status(wallet)}): $error');
  }
  final address = monero.Wallet_address(wallet, accountIndex: 0, addressIndex: 0);
  // Stagenet standard addresses start with '5'; mainnet with '4'. Belt and
  // braces on the one promise these wallets make.
  if (address.startsWith('4')) {
    throw StateError('$path derived a MAINNET address — a published seed must not');
  }
  monero.Wallet_store(wallet, path: path);
  monero.WalletManager_closeWallet(wm, wallet, false);
  return address;
}
