// Generated by tool/make_test_pki.sh. Do not edit by hand.

/// A throwaway PKI for TLS tests: a root, an intermediate, and server
/// certificates that are valid, issued for the wrong host, or from a root the
/// wallet does not trust.
///
/// Every private key is published right here. Nothing these certificates sign
/// is trustworthy, and none of them may reach a production trust store.
class TestPki {
  TestPki._();

  /// A name the wallet treats as routable, so it insists on TLS. Nothing
  /// resolves it: tests reach it through `SocksTestProxy`, which maps it to a
  /// local server the way Tor carries a name to its destination.
  static const routableHost = 'wallet-tls.test';

  /// The trust anchor: the only certificate a test hands the wallet as its CA bundle.
  static const rootCa = '''
-----BEGIN CERTIFICATE-----
MIIBfzCCASSgAwIBAgIIWBmzAeGoMcYwCgYIKoZIzj0EAwIwIjEgMB4GA1UEAwwX
V2FsbGV0IFRMUyBUZXN0IFJvb3QgQ0EwIBcNMjYxMDAzMTUxMTQxWhgPMjEyNjA5
MDkxNTExNDFaMCIxIDAeBgNVBAMMF1dhbGxldCBUTFMgVGVzdCBSb290IENBMFkw
EwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE1O4SUvwbmOwOxNRo6lsWjRNY2Bo+/+hc
C5OOYZ4jolnejOCdxxWX4OtIAHBaMdPjGz7LfwXDEdYpBxKgE2FsBKNCMEAwDwYD
VR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYEFHroHEw2YVPB
1lj55AnOS22NSG7vMAoGCCqGSM49BAMCA0kAMEYCIQDc5wA6j36+QfbdydvbUH+3
GNpizeGjGMxQvWohXMVZewIhAPVrW3YCFiURc63wwoiuiwBYpOzSpI0fPkRxdZhB
I7cD
-----END CERTIFICATE-----
''';

  /// Issued by [rootCa]. Servers send it after their leaf, so chain building is exercised.
  static const intermediateCa = '''
-----BEGIN CERTIFICATE-----
MIIBqzCCAVGgAwIBAgIJAIFVrAj09D1gMAoGCCqGSM49BAMCMCIxIDAeBgNVBAMM
F1dhbGxldCBUTFMgVGVzdCBSb290IENBMCAXDTI2MTAwMzE1MTE0MVoYDzIxMjYw
OTA5MTUxMTQxWjAqMSgwJgYDVQQDDB9XYWxsZXQgVExTIFRlc3QgSW50ZXJtZWRp
YXRlIENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEsDl6+bMdcYoZmTppkX2W
Mnw7uwHN2Pph3d8tSRo7Kj2dY6fgVaWBcHlSnBChaY/vkr7O0UQ87CzuziY05WWb
66NmMGQwEgYDVR0TAQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0O
BBYEFE+hhn6QzR+x1TCCIxr8N8UQxn2tMB8GA1UdIwQYMBaAFHroHEw2YVPB1lj5
5AnOS22NSG7vMAoGCCqGSM49BAMCA0gAMEUCIQCZWeFb7KiFHBuDLj1E1IVCX31y
YzUaNrEpT8lwK+wYDQIgbr7z0nMGDnDVkUEkcSlnbFijtIGTidp6Q3dfMZIQykk=
-----END CERTIFICATE-----
''';

  /// Valid for `localhost`, [routableHost], 127.0.0.1 and ::1; issued by [intermediateCa].
  static const serverCert = '''
-----BEGIN CERTIFICATE-----
MIIB7DCCAZKgAwIBAgICEAAwCgYIKoZIzj0EAwIwKjEoMCYGA1UEAwwfV2FsbGV0
IFRMUyBUZXN0IEludGVybWVkaWF0ZSBDQTAgFw0xOTA2MDEwMDAwMDBaGA8yMTI2
MDEwMTAwMDAwMFowGjEYMBYGA1UEAwwPd2FsbGV0LXRscy50ZXN0MFkwEwYHKoZI
zj0CAQYIKoZIzj0DAQcDQgAEUGLcLuLYCHlNbPV00tdlAYE8Ai47RKyXxs1QS7ZN
NzZinGHBeQGJsX5jLXUs+nCOKuAE0ajSkji0J4JjoRKvyqOBtTCBsjAMBgNVHRMB
Af8EAjAAMA4GA1UdDwEB/wQEAwIHgDATBgNVHSUEDDAKBggrBgEFBQcDATA9BgNV
HREENjA0gglsb2NhbGhvc3SCD3dhbGxldC10bHMudGVzdIcEfwAAAYcQAAAAAAAA
AAAAAAAAAAAAATAdBgNVHQ4EFgQU2C4JhUfWW2BwEksr5liSmGe/HNUwHwYDVR0j
BBgwFoAUT6GGfpDNH7HVMIIjGvw3xRDGfa0wCgYIKoZIzj0EAwIDSAAwRQIgHHnB
dAW5R+eqs4lyxywAuJBpL2GVi2lCCPNV/ZYvhDICIQDctRqnwju6ggEzzyLWW2iE
Gl3wX7mEKdIDRy0bEudIzw==
-----END CERTIFICATE-----
''';

  static const serverKey = '''
-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQglJl+uZU6KM8V8Epw
sIYwy4JaOjjCJ9hkKqfglt2GUwKhRANCAARQYtwu4tgIeU1s9XTS12UBgTwCLjtE
rJfGzVBLtk03NmKcYcF5AYmxfmMtdSz6cI4q4ATRqNKSOLQngmOhEq/K
-----END PRIVATE KEY-----
''';

  /// Chains to [rootCa] but names only `wrong-host.test`.
  static const wrongHostCert = '''
-----BEGIN CERTIFICATE-----
MIIByjCCAW+gAwIBAgICEAEwCgYIKoZIzj0EAwIwKjEoMCYGA1UEAwwfV2FsbGV0
IFRMUyBUZXN0IEludGVybWVkaWF0ZSBDQTAgFw0xOTA2MDEwMDAwMDBaGA8yMTI2
MDEwMTAwMDAwMFowGjEYMBYGA1UEAwwPd3JvbmctaG9zdC50ZXN0MFkwEwYHKoZI
zj0CAQYIKoZIzj0DAQcDQgAEyan2dNt3i8+iuWZls9j5h9RproG6wmcSAxA6O13x
otsg/9znqXup8T11BJWP7jM5M1aVeDWRKkW7YQys8Cne/6OBkjCBjzAMBgNVHRMB
Af8EAjAAMA4GA1UdDwEB/wQEAwIHgDATBgNVHSUEDDAKBggrBgEFBQcDATAaBgNV
HREEEzARgg93cm9uZy1ob3N0LnRlc3QwHQYDVR0OBBYEFFK0SJ7sx5Bh9hAqwLMU
H7ui8BByMB8GA1UdIwQYMBaAFE+hhn6QzR+x1TCCIxr8N8UQxn2tMAoGCCqGSM49
BAMCA0kAMEYCIQD+qQzOk9jirFe+ia07Lw9UjGdFGBwJhihmhmIfbuNZGQIhALdK
EyJGQTHhYumlYSrcY3IUjcNOnKBx60Lxlq7BvNI8
-----END CERTIFICATE-----
''';

  static const wrongHostKey = '''
-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgrEd001maiad5t2vi
ZYexOMp2Zjfla+X2n4yeIljROiahRANCAATJqfZ023eLz6K5ZmWz2PmH1GmugbrC
ZxIDEDo7XfGi2yD/3Oepe6nxPXUElY/uMzkzVpV4NZEqRbthDKzwKd7/
-----END PRIVATE KEY-----
''';

  /// A root the wallet is never given.
  static const untrustedCa = '''
-----BEGIN CERTIFICATE-----
MIIBfjCCASOgAwIBAgIJAOgGPmaRN2FgMAoGCCqGSM49BAMCMCExHzAdBgNVBAMM
FlVudHJ1c3RlZCBUZXN0IFJvb3QgQ0EwIBcNMjYxMDAzMTUxMTQxWhgPMjEyNjA5
MDkxNTExNDFaMCExHzAdBgNVBAMMFlVudHJ1c3RlZCBUZXN0IFJvb3QgQ0EwWTAT
BgcqhkjOPQIBBggqhkjOPQMBBwNCAAR6IW4g0ZyGD21IEX47hwVqaRmkCqyY01wv
8e5Cb//8e/OIGINwc9usH+mtlByQq6xDxHrn3Oc6lHKZy2mxdsY1o0IwQDAPBgNV
HRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBBjAdBgNVHQ4EFgQUjlR9q8HtdjM9
gkiR+uw3glGTbvowCgYIKoZIzj0EAwIDSQAwRgIhAMbFjNmSrnKQ92SpY3b0CAxH
E2oCH9ZD8ZHRbKCOA6iZAiEA9n5tK7CTW6scpNesUCnVwFSSMP90RkpmioXD7r8I
Wdk=
-----END CERTIFICATE-----
''';

  /// Names the same hosts as [serverCert] but chains to [untrustedCa].
  static const untrustedServerCert = '''
-----BEGIN CERTIFICATE-----
MIIB4jCCAYmgAwIBAgICEAIwCgYIKoZIzj0EAwIwITEfMB0GA1UEAwwWVW50cnVz
dGVkIFRlc3QgUm9vdCBDQTAgFw0xOTA2MDEwMDAwMDBaGA8yMTI2MDEwMTAwMDAw
MFowGjEYMBYGA1UEAwwPd2FsbGV0LXRscy50ZXN0MFkwEwYHKoZIzj0CAQYIKoZI
zj0DAQcDQgAEtLgGXlR3eIy3t5cn92E3iK12UkQHAR6Gvfxpaaq2fyAkDUnIWnO3
ORY8p0I4VUMaWetTuyOYZ2d+9B37goO3QqOBtTCBsjAMBgNVHRMBAf8EAjAAMA4G
A1UdDwEB/wQEAwIHgDATBgNVHSUEDDAKBggrBgEFBQcDATA9BgNVHREENjA0ggls
b2NhbGhvc3SCD3dhbGxldC10bHMudGVzdIcEfwAAAYcQAAAAAAAAAAAAAAAAAAAA
ATAdBgNVHQ4EFgQUH965poSKuSRW5B9loVRYSutQlm0wHwYDVR0jBBgwFoAUjlR9
q8HtdjM9gkiR+uw3glGTbvowCgYIKoZIzj0EAwIDRwAwRAIgU5/qmlawxVyPqBzp
fPHoC5eintKDUZ/g1pMLmi9bInoCIEmnNBbYMmc44aYV/JUiSDD4Ql92LK+82YNN
qm3Aop+i
-----END CERTIFICATE-----
''';

  static const untrustedServerKey = '''
-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgw4Xqufaf0VBH0SeS
u52xuuVy5Ky8jTnTiz6J/EpWP7GhRANCAAS0uAZeVHd4jLe3lyf3YTeIrXZSRAcB
Hoa9/GlpqrZ/ICQNSchac7c5FjynQjhVQxpZ61O7I5hnZ370HfuCg7dC
-----END PRIVATE KEY-----
''';

  /// [serverCert] followed by its issuer, as a server sends it.
  static const serverChain = serverCert + intermediateCa;

  /// [wrongHostCert] followed by its issuer.
  static const wrongHostChain = wrongHostCert + intermediateCa;
}
